### ISSUE TITLE
Kitsu export doesn't work if hentai is contained in the anime list

### ISSUE THREAD

**Issue by anonreport** [Atelier-Shiori/Nekomata#1]
Only did minimal testing. I tried exporting my list which contained 2 hentai animes which failed. So I changed my profile's name and profile url to the same name with no special characters to see if it would work. This failed. Next I tried someone else's profile that contained no hidden content to users without an account and it succeeded. Users without an account cannot see hentai and after removing the 2 hentai from my list, the export was successful. And by failed I mean the prompt, "Could not receive list...ect." pops up.

**Comment by moyitpro** [comment]
Currently, Nekomata can't retrieve adult titles since it cannot authenticate, thus it cannot export any adult titles or private entries. This is because I haven't implemented OAuth authentication yet. At the time being, it's not a planned feature as Apps that I receive donations for (Hachidori and Shukofukurou) gets priority over this app.

**Comment by moyitpro** [comment]
Updated answer.
